CREATE TABLE tt_content (
	tx_microtemplate_c_classes varchar(25),
	tx_microtemplate_c_aligncontent varchar(25),
  tx_microtemplate_c_framepadding int(1) DEFAULT '0' NOT NULL,
	tx_microtemplate_c_fullwidth int(1) DEFAULT '0' NOT NULL,
  tx_microtemplate_c_fullheight int(1) DEFAULT '0' NOT NULL,
  tx_microtemplate_c_vcenter int(1) DEFAULT '0' NOT NULL,
	tx_microtemplate_c_textcolorselect varchar(25),
	tx_microtemplate_c_textcolor varchar(25),
	tx_microtemplate_c_bgcolorselect varchar(25),
	tx_microtemplate_c_bgcolor varchar(25),
	tx_microtemplate_c_bgimagewidth varchar(25),
	tx_microtemplate_c_bgimgeffect varchar(25),
	tx_microtemplate_c_bgvideosound int(1) DEFAULT '0' NOT NULL,
  tx_microtemplate_c_bgvideoclearframe int(1) DEFAULT '0' NOT NULL,
  tx_microtemplate_c_bgvideoonoloop int(1) DEFAULT '0' NOT NULL,
	tx_microtemplate_c_bgplacement varchar(25),
	tx_microtemplate_c_bgfixed int(1) DEFAULT '0' NOT NULL,
	tx_microtemplate_c_bgoverlay varchar(25),
	tx_microtemplate_c_bgoverlaydark varchar(25),
	tx_microtemplate_c_bgoverlayopacity varchar(25),
);
